<p>
	<strong>Olimare SG: Tagesschule & Colegio “San Gerardo”.</strong>
</p>
<address>
	<strong>Edificio Central:</strong><br>
	Bernardo Valdivieso 11-71 y Mercadillo.<br>
	Teléfono 07 258 5658 / Fax 07 258 7066
</address>
<address>
	<strong>Campus La Pompeya:</strong><br>
	Km. 3.5 vía a Vilcabamba.<br>
	Teléfono 07 254 5744 / Fax 07 254 5743

</address>
<p>
	<strong>Correo Electrónico:</strong><br><a href="mailto:olimaresg@sangerardo.edu.ec">olimaresg@sangerardo.edu.ec</a><br><a href="mailto:olimarekids1@sangerardo.edu.ec">olimarekids1@sangerardo.edu.ec</a><br><a href="mailto:olimarekids2@sangerardo.edu.ec">olimarekids2@sangerardo.edu.ec</a>
</p>
<p>
	<strong>Horario de atención:</strong><br>Lunes a Viernes de 07:15 a 15:15.<br>
	<a href="http://www.sangerardo.edu.ec" target="_blank">www.sangerardo.edu.ec</a><br>
	Loja - Ecuador
</p>