<p>
	<strong>Puntajes por Niveles</strong> (pr&oacute;ximamente)
</p>
<p>
	<strong>Soluciones por Niveles</strong>
</p>
<ul>
	<li>
		Nivel 1 Octavo - <a href="docs/Soluciones por Niveles/Nivel 1 Octavo.pdf" target="_blank">Descargar</a>
	</li>
	<li>
		Nivel 2 Noveno - <a href="docs/Soluciones por Niveles/Nivel 2 Noveno.pdf" target="_blank">Descargar</a>
	</li>
	<li>
		Nivel 3 Decimo - <a href="docs/Soluciones por Niveles/Nivel 3 Decimo.pdf" target="_blank">Descargar</a>
	</li>
</ul>