<?php $archivo = $this->archivo ?>
<div class="row">
	<div class="col-lg-2">
		<img src="img/olimare-logo.jpg" class="img-responsive center-block">
	</div>
	<div class="col-lg-8">
		<a href="<?php echo $archivo ?>" target="_blank" class="btn btn-primary btn-lg">
			<span class="glyphicon glyphicon-download-alt"></span> Descargue su ficha de inscripción
		</a>
	</div>
	<div class="col-lg-2">
		<img src="img/sg-logo.jpg" class="img-responsive center-block">
	</div>
</div>