<p>
	<strong>Contenidos de las pruebas.</strong>
	<br><br>
	Las pruebas consistirían de 10 preguntas relacionadas con los siguientes temas:
</p>
<ul>
	<li>Geometría: Figuras geométricas, origami (doblez de papel), geometría pura.</li>
	<li>Aritmética: operaciones aritméticas con números reales, proporciones (regla de tres), factorización, máximo común divisor y mínimo común múltiplo.</li>
	<li>Álgebra: expresiones algebraicas, operaciones con polinomios, ecuaciones e inecuaciones, relaciones, funciones (propiedades, dominio, imagen y composición).</li>
</ul>
<p>
	<strong>La inscripción en las Olimpiadas.</strong>
	<br><br>
	La participación en las olimpiadas no es particular, sino institucional. Por tal razón, son las instituciones las que deberán realizar la inscripción según el procedimiento que se indica a continuación:
</p>
<ul>
	<li>Número de participantes: mínimo  uno máximo ocho participantes por nivel.</li>
	<li>Pago: cada institución educativa deberá cancelar dos rubros para asegurar la participación de sus estudiantes en las Olimpiadas por la inscripción de los estudiantes de la misma.</li>
	<li>El valor de la inscripción de los participantes de la institución tendrá un costo de 5 USD, por estudiante. </li>
	<li>Cada institución deberá pagar el valor de la inscripción  de acuerdo a lo establecido por los directivos.</li>
	<li>Registro: la institución deberá registrar su participación mediante La aplicación web online que estarán  activa en la página web del Tagesschule & Colegio “San Gerardo”: www.sangerardo.edu.ec  hasta las 15:00 del último día de inscripción.  En estos formularios, la institución ingresará la siguiente información:
		<ol type="a">
			<li>
				Datos sobre la institución:
				<ol>
					<li>Nombre</li>
					<li>Dirección</li>
					<li>Ciudad</li>
					<li>Teléfono</li>
					<li>Correo electrónico</li>
				</ol>
			</li>
			<li>Lista de estudiantes según los niveles </li>
			<li>
				Datos del representante de la institución ante OLIMARE SG
				<ol>
					<li>Nombre</li>
					<li>Teléfono</li>
					<li>Correo electrónico</li>
				</ol>
			</li>
		</ol>
	</li>
</ul>
<p>
	<strong>Importante.</strong>
	<br><br>
	Si por alguna razón una institución decidiera no participar luego de haber realizado el pago y/o el registro, podrá solicitar el reembolso de los valores cancelados una semana antes del concurso. Para ello deberá devolver el registro de pago correspondiente de ser el caso.
</p>