<p>
	<strong>Normativo de las Olimpiadas.</strong>
	<br><br>
	<strong>• De Tagesschule & Colegio “San Gerardo”</strong>
</p>
<ul>
	<li>Propiciar un ambiente adecuado para rendir las pruebas.</li>
	<li>Garantizar la transparencia del concurso.</li>
	<li>Brindar información oportuna.</li>
	<li>Proporcionar los útiles necesarios para el desarrollo de las pruebas.</li>
	<li>Entregar medallas y diplomas a los ganadores.</li>
	<li>Impartir una charla sobre el Método Montessori, durante el rendimiento de pruebas a los acompañantes (docentes y familiares de las instituciones participantes).</li>
	<li>Ofrecer un refrigerio durante el receso a los participantes y representantes de cada una de las instituciones.</li>
	<li>Solucionar los inconvenientes en caso de presentarse.</li>
</ul>
<p>
	<strong>• De los participantes</strong>
<ul>
	<li>Los participantes son única y exclusivamente aquellos y aquellas estudiantes pertenecientes a las instituciones educativas de la provincia que hayan realizado el pago y el registro correspondientes, mediante el procedimiento indicado.</li>
</ul>
<p>
	<strong>• Del representante de la institución educativa</strong>
</p>
<ul>
	<li>Cada institución educativa deberá nombrar un representante, el cual tendrá las siguientes funciones:
		<ol>
			<li>Actuará como el vínculo entre la institución participante y Olimare SG.</li>
			<li>Informará adecuada y oportunamente a las autoridades, estudiantes y padres de familia sobre el las disposiciones de participación en las Olimpiadas.</li>
			<li>Inscribirá a las y los estudiantes de su institución para participar las Olimpiadas, en la página web www.sangerardo.edu.ec.</li>
			<li>Los datos que deberán ser ingresados sobre cada participante son los siguientes:
				<ul>
					<li>Nombre.</li>
					<li>Año de Educación Básica.</li>
				</ul>
			</li>
			<li>Coordinará los pagos correspondientes por la participación de la institución que representa, según se indicó.</li>
			<li>Coordinará con las autoridades de la institución los desplazamientos de los participantes a la sede en donde se llevarán a cabo las olimpiadas.</li>
			<li>Deberá presentarse a las instalaciones del Tagesschule & Colegio “San Gerardo”,  el día en que se rinda la prueba,  una hora antes de su inicio, para registrar a los participantes de su institución, portando la documentación que lo acredite como representante de la institución, así como las identificaciones de los participantes que rendirán la prueba y una carta de la secretaría de la institución que certifique los años en que cursan los estudiantes inscritos.</li>
		</ol>
	</li>
</ul>
<p>
	<strong>• De los niveles y categorías</strong>
</p>
<ul>
	<li>Olimare SG tiene una única modalidad de participación: individual. Esto quiere decir, que la competencia no se realiza por equipos, sino que cada estudiante inscrito rendirá la prueba.</li>
	<li>Los niveles establecidos son: Primer Nivel (Octavo Año de Educación Básica), Segundo Nivel (Noveno Año de Educación Básica) y Tercer Nivel (Décimo Año de Educación Básica).</li>
	<li>Los colegios pertenecientes al régimen costa, deberán inscribir a sus estudiantes en el nivel anterior al año de básica aprobado. Es decir los estudiantes de noveno año participarán con los estudiantes de octavo año pertenecientes al régimen sierra y así correspondientemente.</li>
	<li>Cada institución podrá participar hasta con 8 alumnos por cada año de educación básica.</li>
</ul>
<p>
	<strong>• De la competencia</strong>
</p>
<ul>
	<li>Las Olimpiadas Matemáticas Recreativas SG consistirán en una única prueba, que se rendirá el día establecido por los directivos, que contendrá tanto preguntas de opción múltiple como de desarrollo.</li>
	<li>El representante de cada institución educativa inscribirá a los participantes para participar en el evento, según el procedimiento indicado en las responsabilidades del representante de la institución educativa. Para ello, deberá registrar a los estudiantes que participarán en las Olimpiadas, llenando el formulario de inscripción en la página web www.sangerardo.edu.ec.</li>
	<li>Además, el representante deberá coordinar el pago por la inscripción de todos los participantes, según se indicó previamente.</li>
	<li>Solo serán habilitados para participar aquellos estudiantes de las instituciones educativas que hayan realizado tanto el registro como el pago total por la participación de cada estudiante.</li>
	<li>Adicionalmente, Olimare SG,  publicará en su página web, las soluciones de la prueba.</li>
</ul>
<p>
	<strong>• Del comité calificador</strong>
</p>
<ul>
	<li>El comité calificador estará conformado por miembros ajenos al Tagesschule & Colegio “San Gerardo”, de preferencia docentes de Universidades y/o Instituciones Educativas no participantes y tendrá a su cargo la calificación de las pruebas.</li>
	<li>Además, el comité se encargará de emitir los resultados  y de proponer las soluciones a los problemas tomados en las pruebas.</li>
	<li>De estimarlo necesario, el comité calificador podrá requerir la colaboración de personas idóneas pertenecientes a la Institución Organizadora para agilitar el proceso de calificación.</li>
</ul>
<p>
	<strong>• De los exámenes y su calificación</strong>
</p>
<ul>
	<li>La prueba constará de 10 preguntas: 7 de opción múltiple y 3 de desarrollo.</li>
	<li>Cada pregunta tendrá un valor de 10 puntos.</li>
	<li>La duración de las pruebas es de hora y media.</li>
	<li>Los criterios de calificación de las pruebas son los siguientes:
		<ul>
			<li>Si la respuesta a una pregunta de opción múltiple es correcta, se otorgarán 10 puntos a la calificación de la prueba.</li>
			<li>Si la respuesta a una pregunta de opción múltiple es incorrecta, se restarán 5 puntos a la calificación de la prueba.</li>
			<li>Si una pregunta de opción múltiple no es respondida no se otorgará ni se quitará puntaje alguno a la calificación de la prueba.</li>
			<li>La calificación de las preguntas de desarrollo están a criterio del comité calificador.</li>
			<li>Si la respuesta a una pregunta de desarrollo es incorrecta no habrá penalización en la calificación.</li>
			<li>Será declarado ganador o ganadora de las Olimpiadas de cada año de educación básica correspondiente las o los participantes que hayan obtenido la calificación más alta.</li>
		</ul>
	</li>
</ul>
<p>
	<strong>• Los resultados de la competencia.</strong>
</p>
<ul>
	<li>Los nombres de las y/o los ganadores de las Olimpiadas Matemáticas Recreativas SG por cada año de educación básica, se indicarán el mismo día, luego de un receso donde el comité calificará cada una de las pruebas.</li>
	<li>Olimare SG se reserva el derecho de solucionar cualquier controversia en una sesión del directorio junto al comité calificador, en caso de que existiera alguna.</li>
</ul>
<p>
	<strong>• De la premiación</strong>
</p>
<ul>
	<li>Se entregarán medallas de oro, plata y bronce para los ganadores con su respectivo diploma para cada año de educación básica.</li>
	<li>Además, se entregarán diplomas con menciones de honor y participación.</li>
	<li>La premiación se realizará el mismo día de las pruebas.</li>
</ul>