<?php
$mensaje = $this->mensaje;
?>
<div class="row">
	<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
		<form action="login/authenticate" method="post" role="form">
			<?php if (strlen($mensaje)) : ?>
			<div class="form-group has-error">
				<div class="alert alert-danger" role="alert"><?php echo $mensaje ?></div>
			</div>
			<?php endif; ?>
			<div class="form-group">
				<label for="usuario">Usuario</label>
				<input type="text" class="form-control" id="usuario" name="usuario">
			</div>
			<div class="form-group">
				<label for="clave">Password</label>
				<input type="password" class="form-control" id="clave" name="clave">
			</div>
			<button type="submit" class="btn btn-default">Entrar</button>
		</form>
	</div>
</div>