<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title><?php echo isset($this->titulo) ? $this->titulo . ' - ' : '' ?>OLIMARE SG 2014</title>
		<base href="<?php echo $this->ServerUrl($this->baseUrl('/')) ?>" />
		<!-- Bootstrap -->
		<link href="css/bootstrap.css" rel="stylesheet">
		<link href="css/demo_table.css" rel="stylesheet">
		<link href="css/themes/default/default.css" rel="stylesheet">
	    <link href="css/nivo-slider.css" rel="stylesheet">
		<link href="css/main.css" rel="stylesheet">
		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="js/html5shiv.js"></script>
		  <script src="js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="navbar navbar-default">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="sobre-olimare">OLIMARE SG 2014</a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<!-- MENU -->
				<ul class="nav navbar-nav">
					<li class="<?php if ($this->menu == 1) echo 'active' ?>"><a href="sobre-olimare">Sobre OLIMARE</a></li>
					<li class="dropdown <?php if ($this->menu > 20 && $this->menu < 30) echo 'active' ?>">
						<a href="informacion" class="dropdown-toggle" data-toggle="dropdown">Información <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li class="<?php if ($this->menu == 21) echo 'active' ?>"><a href="informacion/reglamento">Reglamento</a></li>
							<li class="<?php if ($this->menu == 22) echo 'active' ?>"><a href="informacion/bases-del-concurso">Bases del Concurso</a></li>
							<li><a href="#">Instituciones Participantes</a></li>
						</ul>
					</li>
					<li class="<?php if ($this->menu == 3) echo 'active' ?>"><a href="inscripciones">Inscripciones</a></li>
					<li class="dropdown <?php if ($this->menu > 40 && $this->menu < 50) echo 'active' ?>">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Recursos y descargas <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li class="<?php if ($this->menu == 41) echo 'active' ?>"><a href="recursos/banco-de-pruebas">Banco de Pruebas</a></li>
							<li class="<?php if ($this->menu == 42) echo 'active' ?>"><a href="recursos/solucionarios">Solucionarios</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Cuadros de honor <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<!--li><a href="#">2011</a></li>
							<li><a href="#">2012</a></li-->
							<li><a href="docs/Cuadro de Honor/2013.pdf" target="_blank">2013</a></li>
						</ul>
					</li>
					<li class="<?php if ($this->menu == 6) echo 'active' ?>"><a href="galeria">Galería</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Puntajes <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="puntajes/ingreso">Ingreso de Puntajes</a></li>
							<li><a href="puntajes/reportes">Reportes</a></li>
						</ul>
					</li>
					<li class="<?php if ($this->menu == 8) echo 'active' ?>"><a href="contacto">CONTACTOS</a></li>
				</ul>
			</div><!-- /.nav-collapse -->
		</div>
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="page-header">
						<h1><?php echo $this->titulo ?></h1>
					</div>
					<div class="jumbotron">
						<?php echo $this->layout()->content; ?>
					</div>
				</div>
			</div>
		</div>
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="js/jquery.min.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="js/bootstrap.min.js"></script>
		<script src="js/jquery.nivo.slider.pack.js"></script>
		<script src="js/main.js"></script>
		<?php if ($this->menu == 3) : ?>
		<script src="js/jquery.dataTables.min.js"></script>
		<script src="js/jquery.blockUI.js"></script>
		<script src="js/jquery.validate.min.js"></script>
		<script src="js/json2.js"></script>
		<script src="js/inscripcion.js"></script>
		<?php endif; ?>
		<?php if ($this->menu == 71) : ?>
		<script src="js/jquery.blockUI.js"></script>
		<script src="js/jquery.validate.min.js"></script>
		<script src="js/puntaje.js"></script>
		<?php endif; ?>
		<?php if ($this->menu == 72) : ?>
		<script src="js/jquery.dataTables.min.js"></script>
		<script src="js/reportes.js"></script>
		<?php endif; ?>
	</body>
</html>