<p>
	<img src="img/banner.jpg" align="right">
	<strong>MATEMÁTICAS RECREATIVAS</strong>
	<br><br>
	Antecedentes
	<br>
	Olimpiadas  Matemáticas Recreativas fue fundada en la ciudad de Loja, por el Tagesschule & Colegio “San Gerardo” en el año lectivo 2008-2009, y desde entonces ha organizado cuatro encuentros anuales entre colegios de esta ciudad para los octavos, novenos y décimos años de educación básica.
	<br><br>
	A partir de este año lectivo, la invitación  se la realizaría a todos los planteles educativos de la Provincia de Loja. En ella pueden participar estudiantes de colegios, ya sean públicos o privados, y que se apeguen tanto al calendario educativo de la región sierra y costa.
	<br><br>
	Se espera que de este evento surjan los  participantes que representaran a la provincia, dentro y fuera del país.
	<br><br>
	Adquiriendo  el compromiso de establecer un certamen regular y con los estándares de los concursos de nivel nacional.
	<br><br>
	Las olimpiadas organizadas, no son competencias estrictamente curriculares; en ellas se busca, sobre todo, incentivar en los participantes la creatividad, la inventiva, el espíritu crítico mediante un enfoque lúdico de las matemáticas y en los niveles superiores, la capacidad de abstracción y deducción, características medulares de la actividad  matemática, aplicables y necesarias en la vida cotidiana, los estudios universitarios y la vida profesional.
	<br><br>
	Objetivo General:
</p>
<ul>
	<li>Efectuar las Olimpiadas Matemáticas Recreativas SG a nivel provincial, con los niveles octavo, noveno y décimo años de Educación Básica.</li>
</ul>
<p>
	Objetivos Específicos:
</p>
<ul>
	<li>
		Cultivar el entusiasmo y curiosidad en los niños y jóvenes de nuestra provincia por el estudio de la matemática.
	</li>
	<li>Afianzar  en las instituciones educativas de la provincia de Loja la participación en eventos relacionados con el quehacer matemático, como lo son las olimpiadas matemáticas recreativas.</li>
	<li>Estimular la resolución de problemas matemáticos en un ambiente de amistad y compañerismo.</li>
	<li>Incentivar en la sociedad lojana el reconocimiento de las matemáticas como una herramienta que forma parte de su cultura y que propicia la libertad del individuo al proveerle de capacidades de razonamiento y deducción.</li>
	<li>Colaborar con las instituciones de educación básica en la formación matemática de niños y jóvenes.</li>
	<li>Destacar y reconocer el talento matemático de los niños y jóvenes.</li>
	<li>Obtener el conocimiento y reconocimiento de nuestro trabajo en las Olimpiadas por parte de las Instituciones Educativas a nivel Provincial.</li>
	<li>Promover la participación de los más destacados competidores, representando la provincia y/o respectivo cantón en competencias nacionales.</li>
</ul>