<div class="slider-wrapper theme-default">
	<div id="slider" class="nivoSlider">
		<img src="img/galeria/1.jpg" alt="">
		<img src="img/galeria/2.jpg" alt="">
		<img src="img/galeria/3.jpg" alt="">
		<img src="img/galeria/4.jpg" alt="">
		<img src="img/galeria/5.jpg" alt="">
		<img src="img/galeria/6.jpg" alt="">
		<img src="img/galeria/7.jpg" alt="">
		<img src="img/galeria/8.jpg" alt="">
		<img src="img/galeria/9.jpg" alt="">
		<img src="img/galeria/10.jpg" alt="">
	</div>
</div>